### ISSUE TITLE
Apply rounded corners to UI in auth flow

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#127]
See [design](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=1606%3A10269).

**Comment by yasht01** [comment]
@rubenhorn I had completed working on this in #84 . Can you have a look at it after I fix the merge conflicts?

**Comment by rubenhorn** [comment]
> @rubenhorn I had completed working on this in #84 . Can you have a look at it after I fix the merge conflicts?

Sure. So you are working on resolving them atm?

**Comment by yasht01** [comment]
Yeah. The PR has been open for quite some time that's why some of the latest changes have created merge conflicts.

**Comment by Xazin** [comment]
PR has been merged and this issue should be resolved.
