### ISSUE TITLE
[BUG]: CrowdAction Participation Screen Overflow

### ISSUE THREAD

**Issue by wizlif** [CollActionteam/collaction_app#129]
The `participate in crowdaction` dialog overflows when description is too long

1. Go to a crowdaction's details with a long description
2. Click on participate
4. See a bottom overflow error

**Expected behavior**
Large content should be scrollable

**Screenshots**
![Screenshot_20220104_075803](https://user-images.githubusercontent.com/15793624/148012167-e06e896b-520b-46e9-882f-66f2053cbe08.png)

**Comment by rubenhorn** [comment]
This is already fixed/will be fixed by #132
