### ISSUE TITLE
[SUGGESTION]: Deploy appbundle to Firebase Distribution

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#141]
Instead of APKs, distribute app bundles to testers using Firebase Distribution using GitHub Actions.
* [x] App is live on Google Play
* [x] Workflow step for building and signing APK is removed
* [x] Workflow step for uploading build to Firebase uploads app bundle instead

**Comment by Xazin** [comment]
@rubenhorn Status? 😂

**Comment by rubenhorn** [comment]
> @rubenhorn Status? 😂

Will tackle this after the app is live 😉
