### ISSUE TITLE
[SUGGESTION]: View onboarding from settings

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#143]
If the user wants to view the onboarding again, they could be able to start it again from the settings screen.
👉 Add button to settings screen "What are crowdactions?" that pushes the onboarding route.

(Relates to #142)

**Comment by Xazin** [comment]
Let's ask Niklas to put it in the design so we can implement this with the correct text.

**Comment by laschnik** [comment]
<img width="601" alt="Bildschirmfoto 2022-02-08 um 14 40 10" src="https://user-images.githubusercontent.com/44906984/152998633-4f2c23be-38c9-4836-83b9-3e4a16bd2e6b.png">

Design done. Regarding the label of this list item, let's call it what it is: _onboarding_
Icon ([rocket.svg](https://drive.google.com/file/d/1sSxbzTA9kdnTxccvFBv886rrENcVz-VN/view)) is in the icon folder
