### ISSUE TITLE
[BUG]: Icons on settings page

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#144]
* [ ] Use different icon for external links (opens web browser)
* [ ] Use correct icon for logout from design

(see https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=1609%3A12826)

**Comment by yasht01** [comment]
@rubenhorn so will the external link icon be replaced for `Terms of use`, `Privacy Policy` and `Open Source`?

**Comment by rubenhorn** [comment]
Yes, but this is probably not a priority for the MVP
