### ISSUE TITLE
[SUGGESTION]: Network image loading indicator

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#154]
Add loading indicator to all network images

**Comment by wizlif** [comment]
I've done this for the details page using shimmer. Other images only use a provider. I'm not sure how we can implement those.

**Comment by Xazin** [comment]
@yasht01 If you need help let me or @wizlif know 👍

**Comment by sudo-saksham** [comment]
Since, Yash is working on some other issue. I'm assigning this issue to myself.
