### ISSUE TITLE
[SUGGESTION]: Screen loading indicator

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#155]
Add loading indicator to screens:
* [x] Crowdaction details
* [x] Profile

**Comment by Xazin** [comment]
Let's discuss this shortly after MVP is released. I believe we were thinking of going with shimmer loading, by following Niklas skeleton design. It should be fairly simple to implement, and also has a UX benefit.

**Comment by laschnik** [comment]
Components with skeleton variant
[Title](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=2504%3A17241)
[Card small](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=387%3A1802)
[Invitation](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=1617%3A13040)
[Card large](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=221%3A1362)
[Commitment](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=765%3A4709)
[Badge](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=765%3A4847)
[Banner](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=2074%3A22423)

**Comment by Xazin** [comment]
I think this is more or less resolved. - If not we can reopen, but closing it for now.
