### ISSUE TITLE
[SUGGESTION]: Build information on settings page

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#161]
Show information about the current build on the settings page:
* [x] Build number
* [x] Version name (e.g. 1.0.1)
* [ ] Commit hash (?)
* [x] Target environment (dev/prod, replaces #135)

**Comment by Xazin** [comment]
I'm not sure about the commit hash. And for the target environment, as long as we don't include it in release builds then it should be good.

**Comment by wizlif** [comment]
Is this already included in the design ??

**Comment by laschnik** [comment]
Will take care of it today

**Comment by laschnik** [comment]
- [Link to Figma frame](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=1269%3A19263)
- [Emoji image asset](https://drive.google.com/open?id=1LiXaPml-BujdftWAW_f6R5Hja3AZmkxJ&authuser=niklas%40collaction.org&usp=drive_fs)
- Text Style: Body
- Color: primary/100

**Comment by rubenhorn** [comment]
@Xazin Is the commit hash and the environment name "prod"/"dev" sensitive information?
Maybe we should set up an internal datastore for build information where we can look up details by build number. (This for some reason does not seem possible with GitHub actions)

**Comment by Xazin** [comment]
> @Xazin Is the commit hash and the environment name "prod"/"dev" sensitive information?
> Maybe we should set up an internal datastore for build information where we can look up details by build number. (This for some reason does not seem possible with GitHub actions)

Sensitive no, internal yes. It's not something a user should see. Commit hash can be discussed, but the environment, makes not much sense tbf.

**Comment by rubenhorn** [comment]
Maybe just add it, if it's not the production environment, so we don't accidentally submit/test the wrong build?
