### ISSUE TITLE
[SUGGESTION]: Open links in webview during auth

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#167]
On the login/registration page(s), links should be opened in the app instead of an external web-browser, so the user is not "kicked out of the auth flow".

* [ ] Use webview on legal links in auth flow
* [ ] Since the plugin opens the webview in fullscreen on Android, create a custom screen with an app bar and embedded webview for Android (see https://github.com/CollActionteam/collaction_app/blob/release/mvp-rc3/lib/presentation/utils/launch_url.dart#L11)

**Comment by akshaykumaru18** [comment]
I would wish to take this up an issue and implement

**Comment by tomsiebring** [comment]
Hi @akshaykumaru18. How's it going?
