### ISSUE TITLE
[Feature]: Implement widgets to accomodate commenting

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#175]
In the near future, we want to allow users to comment on a crowd action, users must be signed in to leave a comment, and for users not logged in they should see a CTA register or login (See design).

**Acceptance criteria:**
- Component for section divider on Crowdaction Details Screen (comments section)
- Vertical ListView of comments, in posted at timestamp ascending (newest first)
- Comment Component
- The comment component should include `time since posted at`, `user avatar`, `user display name`, `message`. Additionally the ability to `Delete` a comment if the comment is owned by the user. (pseudo for now I guess)

See figma for design

**Comment by Xazin** [comment]
@wizlif Hey Isaac, let me know if I can help you with anything here! 👍

**Comment by laschnik** [comment]
Design is done!
**Components**: https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=2788%3A18373
**Flows**: https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=1606%3A10204

**Please note**

- text input field appears in cases 5), 6) when reaching comment section
- show newest 10 comments by default, if more > **_view more comments_** button, on submit: show 10 more comments
- liking and flagging comments available in cases 3),4),5),6)

Also updated the icons in the icon folder. Not sure whether compounding the filled icons worked however. Let me know!

**Comment by Xazin** [comment]
What about the case when one have liked a comment?

**Comment by laschnik** [comment]
@Xazin are you referring to the appearance of the heart icon in this case? https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=2788%3A18234

**Comment by Xazin** [comment]
> @Xazin are you referring to the appearance of the heart icon in this case? https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=2788%3A18234

Yes indeed.

What about when flagging a comment, should we have a dialog where the user can at least choose a reason why?

**Comment by laschnik** [comment]
See the attached photo for the current intended behaviour. Let's keep it simple for now. If the amount of reported – and non-categorized – comments becomes an issue for us to scan at one point, we can implement selecting a (custom) reason (or multiple). Dont think this is necessary for now. Agree?

<img width="1038" alt="Bildschirmfoto 2022-01-28 um 14 55 37" src="https://user-images.githubusercontent.com/44906984/151558977-332db104-9c2b-4983-93fb-6fb7edb2f221.png">

**Comment by wizlif** [comment]
Yea, the flagging could have predefined reasons list (Offensive ...)

**Comment by wizlif** [comment]
Something like this.

![20220128_170454.jpg](https://user-images.githubusercontent.com/15793624/151560626-4c2bd51b-881c-469f-be23-c19cc9d71fe0.jpg)

**Comment by Xazin** [comment]
It's good to think about this before we define the entity for the backend anyway.

**Comment by laschnik** [comment]
<img width="441" alt="Bildschirmfoto 2022-01-31 um 12 20 53" src="https://user-images.githubusercontent.com/44906984/151785073-7f397bc7-494b-4646-ac13-415a8ecfd2cb.png">

[Figma frame](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=978%3A10486
)

Reused the chip component for selecting one or multiple reasons for reporting.

**Comment by wizlif** [comment]
Setup the base for commenting
https://github.com/CollActionteam/collaction_app/pull/304

Comment actions still need some work including:-

- [ ] Like button transitions.
- [ ] Flagging flow.
- [ ] Reply to comment flow.
