### ISSUE TITLE
[Feature]: add share FAB above settings FAB

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#177]
The share floating action button should open the Share app modal (See other implementations for reference).

**Acceptance Criteria:**
- Tapping the share FAB will open the share functionality
- The Settings and Share FAB have different heroTags
- The Settings and Share FAB should be refactored to be stacked above the Column inside the SingleChildScrollView so that it doesn't interfere with the splash from pulling down. (This is currently a bug)

**Comment by sudo-saksham** [comment]
I can work on this issue, therefore I am assigning assigning this to myself.

**Comment by sudo-saksham** [comment]
#207
