### ISSUE TITLE
[Android | Design] App switcher background color

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#18]
The background of the top bar in the app switcher does not match the background color of the app icon.  
This makes the rectangular icon stand out compared to other apps and doesn't look too nice.

**To Reproduce**
1. Open the app
2. Open app switcher

**Expected behavior**
The background color of the top bar in the app switcher should exactly match the background color of the icon (#ffffff).

**Screenshots**
![signal-2021-08-28-120605](https://user-images.githubusercontent.com/5367484/131216934-618f09a3-afc2-44c2-925e-fa6ee38fcac1.jpeg)

**Device information:**
 - Device: Android (Axon 7)
 - OS: 8.0.0
 - Version: 1.0.1

**Comment by Xazin** [comment]
I have made a task for this in our to-do. Good catch!

**Comment by Xazin** [comment]
I checked how the logo looks on my device, and here are some screenshots, maybe we can fix this as well. Need correct resolutions for icons.

Screenshots:
![image](https://user-images.githubusercontent.com/42929161/131222089-dd7cf37f-e797-4c42-b8e4-92add966d705.png)
![image](https://user-images.githubusercontent.com/42929161/131222133-200f335f-4a8f-4896-8927-9d4e69688b10.png)

**Comment by rubenhorn** [comment]
The tool I used to generated the icons from a single image file said not to use a margin (because of iOS).
(Also this was only an interim solution so we don't have the default app icon anymore).
Maybe we should also "fix" this on iOS at the same time so we know it looks good on every platform.
It also generates a 1k icon for the AppStore on iOS, so the input image should have a sufficient resolution.
