### ISSUE TITLE
[BUG]: No padding for password dialog

### ISSUE THREAD

**Issue by wizlif** [CollActionteam/collaction_app#182]
Padding missing for crowdaction password input message
![Screenshot_20220118-211436](https://user-images.githubusercontent.com/15793624/149995781-c63be207-25c3-435e-855e-4d77e665249d.jpg)

**Comment by rubenhorn** [comment]
@wizlif Which device and screen size did you find this on?

**Comment by wizlif** [comment]
My android

**Comment by wizlif** [comment]
Samsung Galaxy J6 720 X 1480 Pixels

**Comment by mumin-ahmod** [comment]
Can I work on this issue?

**Comment by Xazin** [comment]
> Can I work on this issue?

Yes of course, feel free to open a PR.
