### ISSUE TITLE
[Feature]: Changes to the "Sign up now" chip

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#184]
The first chip on all CrowdActions is the "Sign up now" chip, the text should now be conditionally changed to "Open" when `Date Now` is past or equal to `dateLimitJoin` OR IF past or equal to `dateEnd` fields from the respective CrowdAction, and otherwise, it should say "Closed" and the chip color should be changed to Primary/200 (#999999).

.. Very straightforward.

**Comment by wizlif** [comment]
Isn't it only open before the dateEnd
OR IF `before` or equal to `dateEnd`
