### ISSUE TITLE
[Feature]: Grey out commitments when participating

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#185]
We want to have a clear indication of when a user can interact with the commitments on the CrowdAction details screen.

**Stroke:** primary/0
**Fill:** secondary
**Title:** primary/300
**Description:** primary/200

**Acceptance Criteria**
- The disabled commitments must fit the design

**Comment by laschnik** [comment]
Design is done. Deactivated variant of the CommitmentCard.
<img width="550" alt="Bildschirmfoto 2022-02-08 um 14 22 52" src="https://user-images.githubusercontent.com/44906984/152995669-1a0dd68d-f3d2-4351-894e-d6c802db6737.png">

- stroke: primary/0
- fill: secondary
- title: primary/300
- description: primary/200 

@Xazin could you change the description of this ticket accordingly? Thanks a lot!
