### ISSUE TITLE
[BUG]: Increment iOS version

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#187]
**Describe the bug**
TestFlight rejects build using a version that is already published to the AppStore:
`ERROR ITMS-90186: "Invalid Pre-Release Train. The train version '1.0.1' is closed for new build submissions"` (see https://github.com/CollActionteam/collaction_app/runs/4912894886?check_suite_focus=true#step:3:492)

TODO: Increment version identifier in pubspec.

**Comment by rubenhorn** [comment]
This should be done as a chore after every release!

**Comment by Xazin** [comment]
Let's add this to the deploy process (Which we will need to write out for future reference 👍)
