### ISSUE TITLE
[Feature]: Add Lock icon to CrowdActions with Password

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#191]
For the MVP we solved this by adding our lock icon on the image content, since we already have the lock icon, we should make a component for it and add it to the CrowdAction Cards and if needed on the CrowdAction details screen.

This feature will be defined more once the design is finished.

**Comment by laschnik** [comment]
- [Card L](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=221%3A1362) 
- [CrowdAction banner](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=2074%3A22423)

Note that the component is the FAB mini without shadow

No Card S design as of yet

**Comment by laschnik** [comment]
[Card S
](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=387%3A1802)
Component: FAB mini without drop shadow
Icon: icon _lock-sm_ 
Dimensions differ from FAB mini: 32px x 32 px (should be exactly the same height as the _now open_ chip)

<img width="617" alt="Bildschirmfoto 2022-02-25 um 12 16 08" src="https://user-images.githubusercontent.com/44906984/155706193-a9fef87b-42c0-4bce-9408-c21395ae1741.png">
