### ISSUE TITLE
[Bug]: Remove elevation from navigation bar

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#192]
We currently have a minor elevation on the navigation bar, it should be removed to align with the design.

**Acceptance Criteria:**
- BottomNavigationBar doesn't have shadows

**Comment by wizlif** [comment]
Could you share a description of the issue ... still can't figure it out.

**Comment by Xazin** [comment]
BottomNavigationBar by default has 8 elevation if elevation isn't defined. Change the elevation property of `BottomNavigationBar` to `elevation: 0.0`
