### ISSUE TITLE
Deactivate captive screen

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#196]
In order to test new builds internally, the captive screen should be disabled.

**Comment by Xazin** [comment]
Should we remove it completely?

**Comment by rubenhorn** [comment]
No, I think we should just deactivate the condition.
We might want to re-use this later.

**Comment by Xazin** [comment]
> No, I think we should just deactivate the condition. We might want to re-use this later.

Alright, we should probably change how this functions at some point, such that a new update isn't needed to turn on/off the captive page next time we use it.
