### ISSUE TITLE
[Bug]: Icon for OSS Licenses Item is wrong

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#197]
~~**What?** Replace link to repo with screen listing the OSS libs and corresponding licenses (see [design](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=2436%3A16750))~~

~~**How?** using https://pub.dev/packages/flutter_oss_licenses~~

**Edit:**  
Change the icon on the settings screen for OSS Licenses, since it's no longer an external link.

**Comment by wizlif** [comment]
Wasn't that already done ?
![Screenshot_20220208-091357.jpg](https://user-images.githubusercontent.com/15793624/152929016-4fdbc3c8-761d-41ce-acf5-a13088c8b00f.jpg)

**Comment by rubenhorn** [comment]
True.  
In that case, only the icon of the list item on the settings page should be chaned, since it's no longer an external link.

**Comment by Xazin** [comment]
Do we know which icon?

**Comment by rubenhorn** [comment]
![Screenshot_20220208-085146-489.png](https://user-images.githubusercontent.com/5367484/152942094-9433b5f7-d6d3-4175-84a3-72c3277ead47.png)

It should have the same icon as "Contact us".

**Comment by laschnik** [comment]
https://drive.google.com/open?id=1FSlPa71-ZQrjTn0DR83Z-VDlKc6d32YH&authuser=niklas%40collaction.org&usp=drive_fs
