### ISSUE TITLE
[SUGGESTION]: Use first and last name instead of "display name"

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#211]
To encourage users to use their real names, we should ask for first and last name in the app and concatenate them into the display name.  
* This requires changes to the account creation and (edit) profile page.
* It should still be possible to resolve the individual first an last name to e.g. greet the user by first name only
* It should still be possible to show the display name and it should appear as "\<FIRST\> \<LAST\>"
* It should not be (trivially) possible for the user to "break" this implementation

👉 Use [no-break whitespace character (U+00A0)](https://jkorpela.fi/chars/spaces.html) to separate first and last name.  
The display name should be split into first and last name at the first occurrence of this character (allowing for multiple first names using regular whitespace).

* [x] Design specification is updated
* [ ] Design is implemented
* [ ] Both fields (first and last name) have a minimum number of characters
* [ ] Input fields are striped and concatenated using a separator character

**Comment by Xazin** [comment]
@laschnik Can you make this change in the registration screens, to split up the display name to be first name and last name? Both fields will be required and have a minimum of 2 characters.

**Comment by laschnik** [comment]
@Xazin yup, I'll take care of that. @rubenhorn did Tom tell you that we will have First + Last + automatically generated unique userId (which the user can change if desired)?

**Comment by rubenhorn** [comment]
> @Xazin yup, I'll take care of that. @rubenhorn did Tom tell you that we will have First + Last + automatically generated unique userId (which the user can change if desired)?

Is this necessary? We already have a unique user id (although the user cannot change it) as well as a unique phone number.

**Comment by Xazin** [comment]
> > @Xazin yup, I'll take care of that. @rubenhorn did Tom tell you that we will have First + Last + automatically generated unique userId (which the user can change if desired)?
> 
> Is this necessary? We already have a unique user id (although the user cannot change it) as well as a unique phone number.

I also don't think it's necessary, since we don't have mentioning users we don't need this right? We can go on with just first + last name.

**Comment by Xazin** [comment]
@laschnik @rubenhorn 
Ruben, Tom, and I discussed this last Monday and decided to just go with the solution that Ruben described in this ticket. 

If we ever need some functionality where we have to change this, we can implement it then, for now it doesn't make much sense to do so.

**Comment by wizlif** [comment]
So would we allow the 3 name scenario for Last name field ??

**Comment by rubenhorn** [comment]
I think it is up to the user if they want to have `<FIRST FIRST NAME><SECOND FIRST NAME>...` and/or `<FIRST LAST NAME><SECOND LAST NAME> ...`.  
This would only affect them if, at some point, we display only one of the two parts. However I would also consider this to be a less critical edge case.

**Comment by laschnik** [comment]
Alright. As long as users will be able to find and mention people without using that unique identifier, I'm perfectly fine with this. As a user I would expect it to work similarly to a facebook search/mention, whereas people closest to my network appear first and people further away with same name appear last.

**Comment by laschnik** [comment]
Just updated it in the flows
[Registration flow](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=1269%3A19207)
[Settings page](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=1269%3A19263)
