### ISSUE TITLE
[BUG/SUGGESTION]: Navigation bar on webview screens

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#212]
Considering the design of the website linked in the app, we should maybe switch to having a "floating close (x) button" on the right with a transparent navigation bar imstead of the current design:
![Screenshot_20220222-085616-792.png](https://user-images.githubusercontent.com/5367484/155087768-9c8b4deb-bfc5-4918-bce3-b5fee107b8de.png)

**Comment by laschnik** [comment]
You are right! See [here](https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-App?node-id=1269%3A19394) for design
What are you referring to with navigation bar?

**Comment by rubenhorn** [comment]
It's hard to see in this screenshot, but the button for navigating back does not float over the content (white row at the top ...do you call this top bar or navigation bar? 🤔).  
If you scroll the content does not extend to the top of the screen but instead disappears behind this white bar.

**Comment by rubenhorn** [comment]
I think the content should scroll "behind a transparent app bar". (Invisible app bar / appearance of floating close button)  
Alternatively I think the app bar should display some sort of title (determined when launching this screen) to not be so empty.

**Comment by Xazin** [comment]
We can easily do a title, but we can as easily implement the transparent appbar.

**Comment by rubenhorn** [comment]
> We can easily do a title, but we can as easily implement the transparent appbar.

You mean can NOT easily implement transparency?

**Comment by laschnik** [comment]
I prefer a transparent appbar. Such that it looks like this:
<img width="356" alt="Bildschirmfoto 2022-02-25 um 12 08 17" src="https://user-images.githubusercontent.com/44906984/155705114-bd4d3fdc-e4c9-49c8-9146-9368f83b8f46.png">

**Comment by Xazin** [comment]
> > We can easily do a title, but we can as easily implement the transparent appbar.
> 
> You mean can NOT easily implement transparency?

Haha no, I meant it, both solutions are trivial. We just need to decide on one.

I also prefer transparent appbar for the pages, but the page would start at top of the screen, I cannot guarantee that it would look nice.

I will check this out later today and upload a picture so we can make a decision.
