### ISSUE TITLE
[UnitTest]: Implement testing on all DTOs

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#224]
As part of the effort of implementing high coverage in our application, we will need to implement tests for all of our data transfer objects known as DTOs.

For each DTO, we will need:

- A fixture of a CrowdAction's raw JSON as well as the same transformed into a CrowdAction Model.
- Test of the `toDomain()` functionality
- Test of the `fromJson()` functionality

**The DTOs we need to implement tests for are:**
- [x] Profile DTO
- [x] Contact Form DTO
- [x] CrowdAction DTO
- [x] CommitmentOption DTO
- [x] Images DTO
- [x] Participation DTO
- [x] Location DTO
- [x] PageInfo DTO
- [x] Paginated Participations DTO
- [x] Paginated CrowdActions DTO

_Note:_ Find a good way to separate the fixture from the test itself (eg. `/tests/dto/crowdaction/fixtures.dart` and `/tests/dto/crowdaction/tests.dart`), to keep the test file as clean as possible. Remember to use readable names for the variables, and try to explain the tests best as possible, to let others more easily understand the tests.

**Comment by sudo-saksham** [comment]
#233 : added tests for Profile DTOs.

**Comment by yasht01** [comment]
@Xazin tests for `.toJson()` method for ContactFormDTO have already been implemented. Is there anything more to be implemented for the ContactFormDTO?

**Comment by Chnapik** [comment]
Apologies for marking the entire issue closed.  Only meant to mark the Images DTO task as complete.  Have reopened.

**Comment by Xazin** [comment]
Updated with some new DTOs on the list

**Comment by Chnapik** [comment]
All DTO unit tests have been completed and pushed to development.
