### ISSUE TITLE
Setting up Codecov for checking test coverage report.

### ISSUE THREAD

**Issue by sudo-saksham** [CollActionteam/collaction_app#226]
For detailed test coverage report, need to set up Codecov with GitHub actions so that it could track the coverage percentage of this whole application.

**Comment by Xazin** [comment]
Let me know if you need help with Github Workflow 👍

**Comment by sudo-saksham** [comment]
It's done. Checkout the coverage at: https://app.codecov.io/gh/CollActionteam/collaction_app
