### ISSUE TITLE
[BUG]: Profile picture not cleared on logout

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#262]
**Describe the bug**
After logging out, the old profile picture is still shown in the profile tab.

**To Reproduce**
1. Log in
2. Make sure profile picture is set
3. Go to settings
4. Log out
5. Profile picture is still shown (!)

**Expected behavior**
Profile picture should be cleared on logout.

**Device information:**
 - Device: Moto G9 Play
 - OS: Android 11
 - Version + build number: 1.1.0+639

**Comment by developer-rachit** [comment]
Not able to reproduce this bug. @Xazin 
I think after @wizlif fixed this one https://github.com/CollActionteam/collaction_app/pull/280 its auto fixed.

**Comment by Xazin** [comment]
It's not fixed. #280 is unrelated.
