### ISSUE TITLE
[SUGGESTION]: Remove contact button from Settings

### ISSUE THREAD

**Issue by wizlif** [CollActionteam/collaction_app#263]
![Simulator Screen Shot - iPhone 13 - 2022-08-26 at 13 54 56](https://user-images.githubusercontent.com/15793624/186889022-87a4169a-f03f-4c72-8c25-1d289932714a.png)

**Comment by rubenhorn** [comment]
Relates to https://github.com/CollActionteam/collaction_api/issues/35  
(We should mention this in a TODO comment)
