### ISSUE TITLE
[SUGGESTION]: Include ionicons

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#286]
**Is your feature request related to a problem? Please describe.**
We want to include ionicons pre-bundled into the application.

**Comment by developer-rachit** [comment]
Hi, @Xazin @tomsiebring is this only require adding dependency or changing some existing icons to ionicons?
Please confirm.

**Comment by Xazin** [comment]
> Hi, @Xazin @tomsiebring is this only require adding dependency or changing some existing icons to ionicons?
> Please confirm.

This originally stems from @laschnik - so it's up to him what needs to be replaced where. I believe we will keep CollactionIcons though
