### ISSUE TITLE
[UnitTest]: Presentation Layer

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#314]
**Description:**
In an attempt to get code coverage above 50%, we should write unit tests for our Widgets. 

The minimum coverage per PR should be at least 80%, the target should be 90% for each tested widget.

**Home Widgets:**
- [x] CrowdActionCarousel
- [x] CurrentUpcomingLayout
- [x] PasswordModal

**Profile Widgets:**
- [x] BadgesTab
- [x] CommitmentsTab
- [x] CrowdActionsTab
- [x] ProfilePicture
- [x] ProfileTab
- [x] SignupCTA

**Onboarding:**
- [x] OnboardingStep
- [x] OnboardingScreen

**CrowdAction Details:**
- [x] CommitmentBadge
- [x] ConfirmParticipation
- [x] CrowdActionChips
- [x] CrowdActionDetailsBanner
- [x] CrowdActionTitle
- [x] Participants
- [x] ParticipationCountText
- [x] WithdrawParticipation

**CrowdAction Home:**
- [x] InSpotlightHeader
- [x] ShareCollActionButton
- [x] ShareCollActionCard

**Contact Form:**
- [x] ContactForm
- [x] ContactFormScreen

**Authentication:**
- [x] EnterUsername
- [x] LegalNotice
- [x] ProfilePhoto
- [x] VerificationCode
- [x] Verified
- [x] VerifyPhone

**Settings:**
- [x] BuildInformationTile
- [x] SettingsListTile
- [x] ShareCollActionListTile
- [x] SettingsLayout
- [x] SettingsScreen

**Licenses:**
- [x] LicensesPage

**Shared Widgets (Commitments):**
- [x] CommitmentCardList
- [x] CommitmentCard

**Shared Widgets (CustomAppBars):**
- [x] CleanAppBar
- [x] CustomAppBar
- [x] ScrollableAppBar

**Shared Widgets (PinInput):**
- [x] PinInput
- [x] PinTextField

**Shared Widgets (Shimmers):**
- [x] CommitmentCardShimmer
- [x] TitleShimmerLine
- [x] TopParticipantsShimmer

**Shared Widgets:**
- [x] AccentActionChip
- [x] AccentChip
- [x] CenteredLoadingIndicator
- [x] CommitmentCard
- [x] ContentPlaceholder
- [x] CountrySearchDialog
- [x] CrowdActionCard
- [x] CustomFAB
- [x] ExpandableText
- [x] ImageSkeletonLoader
- [x] MicroCrowdActionCard
- [x] MicroLock
- [x] NoRippleBehavior
- [x] ParticipantAvatars
- [x] PhoneInput
- [x] PhotoSelector
- [x] PillButton
- [x] RectangleButton
- [x] RectangularButton
- [x] ReturnElevatedButton
- [x] SecondaryChip
- [x] SignUpChip
- [x] WebViewPage

**IMPORTANT:**
Before you start writing a test, check that what you're testing is act ually used in the application, if it's dead code, please submit a PR with removal of that widget, and we will mark it as deleted on the list above.

**Let's start submitting some PRs for this!**

**Comment by Xazin** [comment]
I'm finished with the above, will continue with:
- [ ] CrowdActionDetailsBanner
- [ ] CrowdActionTitle
- [ ] ShareCollactionButton
- [ ] ShareCollActionCard
- [ ] BadgesTab
- [ ] CommitmentsTab
- [ ] CrowdActionsTab
- [ ] ProfilePicture
- [ ] ShareCollactionListTile
- [ ] CommitmentCard
- [ ] CommitmentCardShimmer
- [ ] TitleShimmerLine
- [ ] TopParticipantsShimmer
- [ ] CenteredLoadingIndicator

**Comment by Xazin** [comment]
Also covered these:
- [x] CommitmentBadges
- [ ] LegalNotice
- [ ] LicensesPage
- [ ] OnboardingScreen
- [ ] OnboardingStep
- [ ] CenteredLoadingIndicator
- [ ] CommitmentCardShimmer
- [ ] CustomAppBar
- [ ] CustomFAB
- [ ] TopParticipantsShimmer

**Comment by andre-tm-hui** [comment]
I will start with the shared widgets:

- [ ] AccentActionChip
- [ ] ContentPlaceholder
- [ ] CountrySearchDialog
- [ ] CrowdActionCard
- [ ] ExpandableText
- [ ] ImageSkeletonLoader
- [ ] MicroCrowdActionCard

**Comment by andre-tm-hui** [comment]
Gonna finish up the rest of the shared widgets:
- [ ] NoRippleBehavior
- [ ] ParticipantAvatars
- [ ] PhoneInput
- [ ] PhotoSelector
- [ ] PillButton
- [ ] RectangleButton
- [ ] RectangularButton
- [ ] ReturnElevatedButton
- [ ] SignUpChip
- [ ] WebViewPage

**Comment by andre-tm-hui** [comment]
Will work on the following:

- [ ] SettingsLayout
- [ ] SettingsScreen
- [ ] CommitmentCardList
- [ ] CommitmentCard
- [ ] CleanAppBar
- [ ] ScrollableAppBar
- [ ] PinInput
- [ ] SelectableChip

**Comment by andre-tm-hui** [comment]
Will work on the following while I wait for clarification on PinInput.

- [ ] ContactForm
- [ ] ContactFormScreen
- [ ] EnterUsername
- [ ] LegalNotice
- [ ] ProfilePhoto
- [ ] VerificationCode
- [ ] Verified
- [ ] VerifyPhone

**Comment by andre-tm-hui** [comment]
Will work on the following:
- [ ] ConfirmParticipation
- [ ] CrowdActionDetailsBanner
- [ ] Participants
- [ ] ParticipationCountText
- [ ] WithdrawParticipation
- [ ] InSpotlightHeader

**Comment by andre-tm-hui** [comment]
Will finish up the remaining widget tests.

- [ ] CrowdActionCarousel
- [ ] CurrentUpcomingLayout
- [ ] PasswordModal
- [ ] ProfileTab
- [ ] SignupCTA
