### ISSUE TITLE
[BUG]: App malfunction if no CrowdActions are fetched

### ISSUE THREAD

**Issue by tomsiebring** [CollActionteam/collaction_app#335]
**Describe the bug**
If there's no open CrowdActions that are running, the app doesn't work

**To Reproduce**
1. No running CrowdAction in DB
2. Open App
3. Blank screen

**Expected behavior**
Normal screen, with instead of the CrowdAction card some message that there's no running CrowdActions at the moment in your area.

**Device information:**
 - Device: iPhone 12
 - OS: iOS 16.2
 - Version + build number: 1.1.0

**Comment by Xazin** [comment]
We need to design empty states
