### ISSUE TITLE
[BUG]: Update AppIcons with new Logo

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#399]
**Describe the bug**
Change App Icons and Launcher Icons to use the new logo.

**Comment by gantanikhilraj** [comment]
Hey @Xazin, I can work on this. Please assign it to me.

**Comment by Xazin** [comment]
> Hey @Xazin, I can work on this. Please assign it to me.

Thank you @gantanikhilraj I have assigned you.

Let me know if you need any help, the logo can be found in Google Drive.

**Comment by Xazin** [comment]
> > > Hey @Xazin, I can work on this. Please assign it to me.
> > 
> > Thank you @gantanikhilraj I have assigned you.
> > 
> > Let me know if you need any help, the logo can be found in Google Drive.
> 
> Where can I find google drive link @Xazin 

https://drive.google.com/drive/folders/1WZmPIU5eVMVXxBVHOyFDh86RTvtVh-Xc

If you don't have access lmk.

**Comment by CollActionOfficial** [comment]
Please find attached the 1024x1024 png. Let me know if you need more
![Frame 1489 (1)](https://user-images.githubusercontent.com/87436073/230322020-e5f34308-f00e-464f-acd4-d50e905e428d.png)

**Comment by gantanikhilraj** [comment]
> Please find attached the 1024x1024 png. Let me know if you need more ![Frame 1489 (1)](https://user-images.githubusercontent.com/87436073/230322020-e5f34308-f00e-464f-acd4-d50e905e428d.png)

In this issue I need change the existing appicon with new icon(above image) which display on the main screen of the phone. Is it @Xazin.

**Comment by Xazin** [comment]
It's on the startup screen, and also the app icon on iOS and Android, see here for reference:
https://stackoverflow.com/a/73357799
https://medium.com/flutter-community/change-flutter-app-launcher-icon-59c31bcd7554
https://www.appicon.co/

**Comment by CollActionOfficial** [comment]
To replace the icons in this file, you can use attached. I'm not sure why these sizes+quality images are used in particular, so if you need others or know something better, let me know :) 
<img width="84" alt="Icon-App-83 5x83 5@2x" src="https://user-images.githubusercontent.com/87436073/230353843-70f7e56f-21f4-4222-9f98-47e7d7b48a0f.png">
<img width="76" alt="Icon-App-76x76@2x" src="https://user-images.githubusercontent.com/87436073/230353844-fc1afa4a-20b6-4948-a9e9-bfa2fa3cd60f.png">
![Icon-App-76x76@1x](https://user-images.githubusercontent.com/87436073/230353846-e16c5e52-95fa-405c-a401-7f57fe3f4c0d.png)
![Icon-App-60x60@3x](https://user-images.githubusercontent.com/87436073/230353848-ac453016-0527-42ec-a844-d31ab5da9652.png)
<img width="60" alt="Icon-App-60x60@2x" src="https://user-images.githubusercontent.com/87436073/230353849-5b78d345-dd75-4be2-89a6-e19fdefab3fa.png">
![Icon-App-40x40@3x](https://user-images.githubusercontent.com/87436073/230353852-ba503681-eee7-498a-aaa2-85ea8bf1a6d0.png)
<img width="40" alt="Icon-App-40x40@2x" src="https://user-images.githubusercontent.com/87436073/230353854-49531d5b-d5fb-4d0c-a732-bf16b80395f2.png">
![Icon-App-40x40@1x](https://user-images.githubusercontent.com/87436073/230353855-e73adca9-4259-4192-aad3-b7a11de1af75.png)
![Icon-App-29x29@3x](https://user-images.githubusercontent.com/87436073/230353858-8d7048d5-5464-4617-a351-084e0518c2c9.png)
<img width="29" alt="Icon-App-29x29@2x" src="https://user-images.githubusercontent.com/87436073/230353861-b0c14dfd-1d9e-44ee-a009-e25daf8d3281.png">
![Icon-App-29x29@1x](https://user-images.githubusercontent.com/87436073/230353862-967a6105-7813-460b-af4e-498a26f9d836.png)
![Icon-App-20x20@3x](https://user-images.githubusercontent.com/87436073/230353863-c6ceb942-957b-4f02-a4fc-551d427c681c.png)
<img width="20" alt="Icon-App-20x20@2x" src="https://user-images.githubusercontent.com/87436073/230353865-fad9d43b-6b3f-46e7-9f95-408363e1bd83.png">
![Icon-App-20x20@1x](https://user-images.githubusercontent.com/87436073/230353866-3b7ab54c-6e8b-4449-9f76-20066c2e0577.png)
![Icon-App-1024x1024@1x](https://user-images.githubusercontent.com/87436073/230353870-60297024-9ad6-4f48-90ac-3d650f2160d9.png)

**Comment by CollActionOfficial** [comment]
[Icon-App.zip](https://github.com/CollActionteam/collaction_app/files/11169702/Icon-App.zip)

**Comment by CollActionOfficial** [comment]
To replace the icons in this file, you can use attached. I'm not sure why these sizes+quality images are used in particular, so if you need others or know something better, let me know :)
[Icon-App.zip](https://github.com/CollActionteam/collaction_app/files/11169707/Icon-App.zip)

**Comment by Xazin** [comment]
> On Android I uploaded the new images on Google Play Store Console (which wasn't possible on Apple's App Store Connect). Maybe it happens automatically on Google through the Console, and for Apple it needs to be done in code? @Xazin what do you think?

It needs to be changed in code as well.

**Comment by tomsiebring** [comment]
@gantanikhilraj how's it going?

**Comment by gantanikhilraj** [comment]
> @gantanikhilraj how's it going?

Sorry, got another plans, can't work on this.

**Comment by sarahaudina** [comment]
I have updated ios AppIcon android's ic_launcher. Do we need to also update android's splash_logo and ios's LaunchImage?
