### ISSUE TITLE
[BUG] Tests not working in 11-graphql-interaction

### ISSUE THREAD

**Issue by FrankTN** [CollActionteam/collaction_app#4]
Running 'example widget test' does not work currently, the line `await initHiveForFlutter();` runs indefinitely. 
This line is required for the GraphQL interaction code to run properly, it initializes a Hive (lightweight db for Flutter), however this does not currently work. When debugging I saw that it gets stuck trying to create a new box, line 30 in the initHiveForFlutter() function,  `await Hive.openBox(box);`. Interestingly, `await initHiveForFlutter();` does not lead to issues in the main app.

Any input from the others is appreciated, for now I won't create a PR until this is resolved.

**Comment by rubenhorn** [comment]
Strangely I can't even start the app on this branch:
```
../../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/uuid_enhanced-3.0.2/lib/uuid.dart:9:7: Error: 'UnmodifiableUint8ListView' is restricted and can't be extended or implemented.
class Uuid extends UnmodifiableUint8ListView {
      ^

FAILURE: Build failed with an exception.
```
I've tried `flutter clean` and `flutter pub cache clean`, but it does not help.

**Comment by MaschavanderMarel** [comment]
I was able to run the app by `flutter run --no-sound-null-safety ` if memory serves me right.

**Comment by FrankTN** [comment]
It should work now, the null-safety checks were added and I updated everything to the latest version.
I have found that I can run the tests if I ensure the correct bindings are initialized (using `TestWidgetsFlutterBinding.ensureInitialized();`), now all that is left is to mock the Http responses, as normal requests are blocked by the test suite.
