### ISSUE TITLE
[Docs]: Add Contribution Guide

### ISSUE THREAD

**Issue by cmedamine** [CollActionteam/collaction_app#76]

**Comment by Xazin** [comment]
This is delayed for the current foreseeable future. We have a SDLC document for the internal team, and we have no view on allowing external PRs currently. We will be adding a contribution guide as soon as we decide our team is mature enough to handle external contributions, and when we have decided on all details.

I think we can keep this open for at least until v1 have been pushed to Master properly.

**Comment by Xazin** [comment]
This is a WiP!
[Contributing Guidelines](https://github.com/CollActionteam/collaction_app/blob/doc/contributing/docs/CONTRIBUTING.md)
