### ISSUE TITLE
[SUGGESTION]: Pre-commit checks

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#79]
Issues with the script:
- Missing `#!/bin/sh` in the first line
- The exit code of the formatting operation is not used: https://github.com/CollActionteam/collaction_app/blob/development/cl.sh#L2

Suggestion:
- Rename script to `./hooks/pre-commit`
- Create a script `./install-hooks` that executes `cp ./hooks/* ./.git/hooks/` (should work with both bash and cmd)

**Comment by rubenhorn** [comment]
May replace https://github.com/CollActionteam/collaction_app/blob/development/cl.sh

**Comment by yasht01** [comment]
Does the `--dry-run` flag work now as it does not appear as a flag on running `flutter format --help`?
If the intention is to not fix the code and only send the output code then we can use `-o none` flag [as this does the intended thing](https://dart.dev/tools/dart-format).

**Comment by yasht01** [comment]
Also, we can just run `flutter format --set-exit-if-changed .` if we need to automatically fix any style errors.

**Comment by Xazin** [comment]
The pre commit check fails a commit if one check fails. But hooks, like a CICD pipeline, should never introduce code changes.

Instead when you make a commit, the pre commit hook should be triggered, it will run the checks (formatter, analyzer) and tell you what's wrong.

**Comment by yasht01** [comment]
Okay so do we need to show the files that need to be formatted in the output or it should just return with the exit code?

**Comment by yasht01** [comment]
>  (should work with both bash and cmd)

@rubenhorn I think Git for Windows installs Git bash by default so will there be a need to create cmd script?

**Comment by rubenhorn** [comment]
Yes, I think there is no such thing as Git without Bourne (Again) Shell aka (ba)sh
