### ISSUE TITLE
[BUG]: Double clicking share button

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#85]
**Describe the bug**
When I double click the "Share CollAction" button on the home screen, the share sheet opens twice and can be closed twice.

**To Reproduce**
1. Open the app on home screen
2. Click two time on "Share CollAction"

**Expected behavior**
The button should be disabled either until the share sheet is closed or with a small delay to make sure that opening multiple share sheets isn't possible.

**Comment by yasht01** [comment]
I tried to think of a solution for this by adding a `Future.delayed()`. It works for now.

https://gist.github.com/yasht01/ab96bf8927014485462957f0ec4aa4c7

**Comment by yasht01** [comment]
@Xazin this issue still persists after merging #104 . I have proposed a fix for this above. Can I go ahead and implement this?
