### ISSUE TITLE
[Feature]: Implement Snackbars for errors and swap 'error text widgets'

### ISSUE THREAD

**Issue by Xazin** [CollActionteam/collaction_app#88]
**Feature:**
We should swap out all Text widgets that display failures such as "NetworkRequestFailed" with something like "No Spotlight CrowdActions right now! Look back alter" and some generic icon. This should be done everywhere where an error may displayed with information that is irrelevant for the user.

**Expected Behavior:**
A network request failure happens when loading Spotlight CrowdActions, a snackbar shows for a few seconds saying "Something went wrong, check your internet connection!", and a widget is displayed properly to enforce UX, instead of just some Text with an error message.

**Comment by laschnik** [comment]
Snackbar component: 
https://www.figma.com/file/dYFW0QF7Fg10dpSIxA3wQb/CollAction-MVP?node-id=1371%3A11484
