### ISSUE TITLE
[BUG]: Back icon on contact form

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#89]
**Describe the bug**
Icon of back button not positioned correctly.

**To Reproduce**
1. Open contact form

**Screenshots**
![Screenshot_20211213-074135.png](https://user-images.githubusercontent.com/5367484/145764633-83cba39e-d2e0-493b-8495-60124fba36c3.png)

**Device information:**
 - Device: moto g9 play
 - OS: Android 11
 - Version + build number: 1.0.0+264

**Comment by yasht01** [comment]
@rubenhorn I think this issue came up after Isaac added custom icons inplace of `.png` images. I'll have a look at this.
