### ISSUE TITLE
[Feature]: "Lockdown mode" after MVP phase

### ISSUE THREAD

**Issue by rubenhorn** [CollActionteam/collaction_app#94]
**Functionality:** Upon resuming or starting the app, the current date should be checked and compared to the MVP deadline. If the MVP phase has ended, instead of the app's content a captive page is displayed.

Implement a condition with a static date for 31st of January 23:59, show captive page if after this date.

**Captive page content:**
See Figma for content

**Captive page design:**
See Figma for full page
<details>
  <summary>Image of Captive Page</summary>

![image](https://user-images.githubusercontent.com/42929161/146980509-12b1b48d-fb34-4603-95f1-edf750f3fb3e.png)

</details>

**Comment by Xazin** [comment]
Captive page design is now in figma
